const USER_CONSTANTS = Object.create(null);

USER_CONSTANTS.USERNAME_MIN_LENGTH = 3;
USER_CONSTANTS.USERNAME_MAX_LENGTH = 20;
USER_CONSTANTS.USER_PASSWORD_MIN_LENGTH = 3;
USER_CONSTANTS.USER_PASSWORD_MAX_LENGTH = 20;

module.exports = USER_CONSTANTS;